/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'

const $nsid = 'com.atproto.server.createAccount'

export { $nsid }

/** Create an account. Implemented by PDS. */
const main =
  /*#__PURE__*/
  l.procedure(
    $nsid,
    /*#__PURE__*/ l.params(),
    /*#__PURE__*/ l.jsonPayload({
      email: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
      handle: /*#__PURE__*/ l.string({ format: 'handle' }),
      did: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'did' })),
      inviteCode: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
      verificationCode: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
      verificationPhone: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
      password: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
      recoveryKey: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
      plcOp: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.unknownObject()),
    }),
    /*#__PURE__*/ l.jsonPayload({
      accessJwt: /*#__PURE__*/ l.string(),
      refreshJwt: /*#__PURE__*/ l.string(),
      handle: /*#__PURE__*/ l.string({ format: 'handle' }),
      did: /*#__PURE__*/ l.string({ format: 'did' }),
      didDoc: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.unknownObject()),
    }),
    [
      'InvalidHandle',
      'InvalidPassword',
      'InvalidInviteCode',
      'HandleNotAvailable',
      'UnsupportedDomain',
      'UnresolvableDid',
      'IncompatibleDidDoc',
    ],
  )
export { main }

export type Params = l.InferMethodParams<typeof main>
export type Input = l.InferMethodInput<typeof main>
export type InputBody = l.InferMethodInputBody<typeof main>
export type Output = l.InferMethodOutput<typeof main>
export type OutputBody = l.InferMethodOutputBody<typeof main>

export const $lxm = /*#__PURE__*/ main.nsid,
  $params = /*#__PURE__*/ main.parameters,
  $input = /*#__PURE__*/ main.input,
  $output = /*#__PURE__*/ main.output
