/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'

const $nsid = 'com.atproto.server.deleteSession'

export { $nsid }

/** Delete the current session. Requires auth using the 'refreshJwt' (not the 'accessJwt'). */
const main =
  /*#__PURE__*/
  l.procedure(
    $nsid,
    /*#__PURE__*/ l.params(),
    /*#__PURE__*/ l.payload(),
    /*#__PURE__*/ l.payload(),
    ['InvalidToken', 'ExpiredToken'],
  )
export { main }

export type Params = l.InferMethodParams<typeof main>
export type Input = l.InferMethodInput<typeof main>
export type InputBody = l.InferMethodInputBody<typeof main>
export type Output = l.InferMethodOutput<typeof main>
export type OutputBody = l.InferMethodOutputBody<typeof main>

export const $lxm = /*#__PURE__*/ main.nsid,
  $params = /*#__PURE__*/ main.parameters,
  $input = /*#__PURE__*/ main.input,
  $output = /*#__PURE__*/ main.output
