/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'

const $nsid = 'com.atproto.server.getSession'

export { $nsid }

/** Get information about the current auth session. Requires auth. */
const main =
  /*#__PURE__*/
  l.query(
    $nsid,
    /*#__PURE__*/ l.params(),
    /*#__PURE__*/ l.jsonPayload({
      handle: /*#__PURE__*/ l.string({ format: 'handle' }),
      did: /*#__PURE__*/ l.string({ format: 'did' }),
      didDoc: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.unknownObject()),
      email: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
      emailConfirmed: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
      emailAuthFactor: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
      active: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
      status: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    }),
  )
export { main }

export type Params = l.InferMethodParams<typeof main>
export type Output = l.InferMethodOutput<typeof main>
export type OutputBody = l.InferMethodOutputBody<typeof main>

export const $lxm = /*#__PURE__*/ main.nsid,
  $params = main.parameters,
  $output = main.output
