/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'

const $nsid = 'com.atproto.server.refreshSession'

export { $nsid }

/** Refresh an authentication session. Requires auth using the 'refreshJwt' (not the 'accessJwt'). */
const main =
  /*#__PURE__*/
  l.procedure(
    $nsid,
    /*#__PURE__*/ l.params(),
    /*#__PURE__*/ l.payload(),
    /*#__PURE__*/ l.jsonPayload({
      accessJwt: /*#__PURE__*/ l.string(),
      refreshJwt: /*#__PURE__*/ l.string(),
      handle: /*#__PURE__*/ l.string({ format: 'handle' }),
      did: /*#__PURE__*/ l.string({ format: 'did' }),
      didDoc: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.unknownObject()),
      email: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
      emailConfirmed: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
      emailAuthFactor: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
      active: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
      status: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    }),
    ['AccountTakedown', 'InvalidToken', 'ExpiredToken'],
  )
export { main }

export type Params = l.InferMethodParams<typeof main>
export type Input = l.InferMethodInput<typeof main>
export type InputBody = l.InferMethodInputBody<typeof main>
export type Output = l.InferMethodOutput<typeof main>
export type OutputBody = l.InferMethodOutputBody<typeof main>

export const $lxm = /*#__PURE__*/ main.nsid,
  $params = /*#__PURE__*/ main.parameters,
  $input = /*#__PURE__*/ main.input,
  $output = /*#__PURE__*/ main.output
